### PR TITLE
Compliance with the standard fix of inserts in vector_multiset and vector_multimap.

### PR DESCRIPTION
**Pull request by wmamrak**

### CODE REVIEW

**Comment by rparolin** [comment]
Can you please include tests that validate this behaviour?

**Comment by rparolin** [comment]
Also the CLA must be signed before I can merge your PR.

**Comment by wmamrak** [comment]
I have added the tests.
Also, I believe I have signed the CLA a few years back.

**Comment by rparolin** [comment]
We don't have a record of it.  Can you please resubmit the CLA?

**Comment by wmamrak** [comment]
> We don't have a record of it. We don't have to delay your PR but can you please resubmit the CLA?

Done!

**Comment by rparolin** [comment]
Excellent!  Thank you.

**Pull request merged**
