### PR TITLE
Fixing problem where eastl::partition on tuple_vector could not compile due to missing swap on eastl::tuple&&

### PR DESCRIPTION
**Pull request by CypherSignal**

### CODE REVIEW

**Comment by CypherSignal** [comment]
I'm not sure what the unit-test failure in mingw_64 is about (failing on misc. string activity?). The change should not affect that in any way. Could it be a spurious error that needs a re-run?

**Comment by rparolin** [comment]
Maybe Travis upgraded the default compiler in their image.  That was the cause last time this happened

**Comment by rparolin** [comment]
That's indeed what happened.  The MingGW GCC version went from 7.3.0 -> 8.2.0.
Sorry, I haven't had time lately to look at it.   But it needs to be resolved before I let any PRs in.

**Comment by rparolin** [comment]
Thanks for the PR!  Apologies for the delay in response.

**Pull request merged**
