### PR TITLE
Fix unmached optional value constructor/destructor calls

### PR DESCRIPTION
**Pull request by zheland**
Fix unmached optional value constructor/destructor calls count.

Optional assignment operator should use
value copy constructor instead value assigment operator
if target optional does not contain a value.

If source optional does not contain a value,
target value destructor should be called.

### CODE REVIEW

**Comment by zheland** [comment]
The added test cases pass on optional implementation for GCC 7.1.0 and Clang 4.0.0

**Comment by rparolin** [comment]
I submitted the new release.  Please resolve conflicts and I will review.

**Comment by zheland** [comment]
Sorry for the delay in replying.
Conflicts resolved, commit updated.
Modified tests succeed on GCC and Clang ( https://godbolt.org/g/xFdrQC ).

**Comment by zheland** [comment]
From updated commit-message:

Optional copy constructor should use inplace constructor
instead copy assigment operator because constructed value,
does not exist yet and assigment operator can not be used.

Optional move constructor should not use swap operation
for engaged flag because according to C++ draft N4762, page 537:
constexpr optional(optional&& rhs) noexcept(see below );
7 Effects: ... bool(rhs) is unchanged.
8 Ensures: bool(rhs) == bool(*this).

Optional assignment operators should use in-place construct
instead value assignment operator if lhs if nullopt.
If rhs is nullopt it should destruct value in lhs.

Also move assigment operator should not use
swap for engaged flag because according to C++ draft N4762, page 539:
optional<T>& operator=(optional&& rhs) noexcept(see below );
8 Effects: ... The result of the expression bool(rhs) remains unchanged.
10 Ensures: bool(rhs) == bool(*this).

Test where unique ptr moved from one to another optional is
incorrect due to after optional moved bool(optional) remains unchanged.
Test fixed and unique_ptr ownership movement check added.

**Comment by rparolin** [comment]
Thanks for the PR!

**Pull request merged**
